CREATE DATABASE fitagotchi;
USE fitagotchi;

CREATE TABLE user_data (
user_id INT PRIMARY KEY AUTO_INCREMENT,
full_name VARCHAR(50),
height INT,
weight INT,
email_address VARCHAR(50),
password VARCHAR(50)
);

insert into user_data (full_name, height, weight, email_address, password)
VALUES 
('Latasha Wall', 162, 66, 'latasha.wall@hotmail.com', 'password123'),
('Jacquline Chapman',170, 53, 'jacquline.chapman@yahoo.com','cheese123'),
('Genoveva Marquez', 187, 91, 'genoveva.marquez@yahoo.com','marqez444'),
('Pamelia Kaufman',146, 43, 'pamelia.kaufman@hotmail.com','Chestnut123'),
('Deshawn Ortiz',145, 56, 'deshawn.ortiz@yahoo.com','cobblestone44'),
('Robby Striker',166, 66, 'robby.striker@hotmail.com','Rockmaple674'),
('Lashawn Gomez',188, 76, 'lashawn.gomez@yahoo.com','longview888'),
('Garry Mendoza',198, 120, 'garry.mendoza@hotmail.com','7rockawayforney'),
('Linnie Leaf',144, 50, 'linnie.leaf@hotmail.com','31columbe'),
('Emmitt Lopez',174, 74, 'emmitt.lopez@hotmail.com','newYorkrules'),
('Caren Stokes',164, 71, 'caren.stokes@yahoo.com','scarsdale99'),
('Georgetta Bell',151, 49, 'georgetta.bell@aol.com','chape776'),
('Lizzette Salvo',159, 60, 'lizzette.salvo@yahoo.com','mill14127'),
('Aleta Ruth', 145, 43, 'aleta.ruth@aol.com','sugarLand8'),
('Tobie Small',163, 48, 'tobie.small@hotmail.com','silvervictor04'),
('Adelle Float',180, 71, 'adelle.float@hotmail.com','birkland1'),
('Kaylee French',183, 76, 'kaylee.french@yahoo.com','plop8977'),
('Corene Hall',168, 65, 'corene.hall@yahoo.com','ocean301'),
('Regenia Bright',149, 50, 'regenia.bright@hotmail.com','mahopac541'),
('Theo Vaught', 149, 44, 'theo.vaught@hotmail.com','hrse1561'),
('Santos Ryall',153, 64, 'santos.ryall@yahoo.com','sunnyside114'),
('Jeanice Chew',156, 44, 'jeanice.chew@hotmail.com','ossining562'),
('Syreeta Hamm',165, 60, 'syreeta.hamm@yahoo.com','hopac9999'),
('Jamaal Draper',164, 56, 'jamaal.draper@hotmail.com','torrance0505'),
('Williemae Willoughby', 154 , 50, 'williemae.willoughby@yahoo.com','ooakland3'),
('Araceli Green',155, 41, 'araceli.green@yahoo.com','fullerton31'),
('Deloris Richards',158, 47, 'deloris.richards@hotmail.com','pass90274'),
('Brittney Plough',173, 74, 'brittney.plough@aol.com','plhillip31'),
('Guillermina King',145, 76, 'guillermina.king@yahoo.com','guill555'),
('Bernita Rogers',174, 65, 'bernita.rogers@hotmail.com','royalnonce333'),
('Melia Brown',145, 46, 'melia.brown@hotmail.com','9maspeth'),
('Zelma Foster',167, 67, 'zelma.foster@aol.com','astoria2'),
('Janetta Wren', 170, 65, 'janetta.wren@aol.com','passsword33'),
('Ronna Iqbal', 168, 66, 'ronna.iqbal@hotmail.com','password90'),
('Kathie North',162, 52, 'kathie.north@yahoo.com','tamagotchi9'),
('Tangela West',165, 64, 'tangela.west@aol.com','tired00'),
('Mozelle East', 177, 73, 'mozelle.east@aol.com','incredibl0'),
('Onita Espinoza', 188, 78, 'onita.espinoza@yahoo.com','zero000'),
('Bennett Snow', 164, 63, 'bennett.bates@aol.com','loopy46'),
('Monika Geller', 145, 61, 'monika.geller@hotmail.com','floopy8'),
('Bridgette Tribbiani', 172, 67, 'bridgette.tribbiani@hotmail.com','sotired8'),
('Cesar Mcclean', 165, 68, 'cesar.mcclean@hotmail.com','saulgoodman3'),
('Caroll Johns',160, 60, 'caroll.johns@yahoo.com','creedbratton88'),
('Cleotilde Schmidt', 145, 50, 'cleotilde.schmidt@hotmail.com','iwishthiswasquicker'),
('Gertrud Walls', 175, 71, 'gertrud.walls@aol.com','rhodey66'),
('Tu Poole', 165, 66, 'tu.poole@hotmail.com','ramirez4eva'),
('Saturnina Steele', 161, 54, 'saturnina.steele@hotmail.com','saturn5'),
('Fran Wong',174, 72, 'fran.wong@hotmail.com','yinyang92'),
('Diana Tate', 166, 54, 'diana.tate@hotmail.com','dianatheg56'),
('Lolita Hobbs',  155, 46, 'lolita.hobbs@hotmail.com','lolita1111'),
('Pamala Payne', 160, 64, 'pamala.payne@aol.com','pamhen1'),
('Damien Sawyer', 163, 65, 'damien.sawyer@yahoo.com','dorseydaisy0'),
('Latasha Mullen', 162, 58, 'latasha.mullen@hotmail.com','stantheman99'),
('Neil Maxwell',188, 69, 'neil.maxwell@hotmail.com','scottmcall123'),
('Elinore Ramos',134, 40, 'elinore.ramos@yahoo.com','eeyore4'),
('Alica Brennan',158, 87, 'alica.brennan@hotmail.com','aliciathehunter'),
('Tenisha Wise', 168, 89, 'tenisha.wise@aol.com','tenlions'),
('Bobbie Webb', 175, 90, 'bobbie.webb@yahoo.com','fosterbob7'),
('Kate Vargas', 163, 85, 'kate.vargas@hotmail.com','vegan4life'),
('Lorrie Aguilar', 164, 68, 'lorrie.aguilar@yahoo.com','beck1and1lor'),
('Tommie Blackwell', 190, 90, 'tommie.blackwell@hotmail.com','tyhffrr887'),
('Jimothy Frost', 164, 65, 'Jimothy.frost@hotmail.com','kuiokuikj'),
('Katelin Board', 163, 52, 'katelin.board@hotmail.com','cfgcfgcfg77777'),
('Tomasa Winston', 154, 78, 'tomasa.winston@aol.com','tomato7'),
('Takako Cowan', 188, 68, 'takako.cowan@aol.com','cakeisgood'),
('Petronila Harrison', 161, 66, 'petronila.harris@aol.com','icecream0'),
('Melanie Robben', 155, 70, 'melanie.robben@yahoo.com','hayho87'),
('George Proctor', 160, 50, 'george.proctor@yahoo.com','gggwallerr4'),
('Abby Perth', 185, 70, 'abby.perth@aol.com','amityville'),
('Parker Noble', 181, 81, 'parker.noble@hotmail.com','jefferson76'),
('Keri Firth',165, 64, 'keri.firth@hotmail.com','bridgetoterabithia'),
('Chi Minty', 154, 60, 'chi.minty@aol.com','goodchi999'),
('Ashanti India', 163, 81, 'ashanti.india@hotmail.com','ploplop'),
('Sarai Stein', 174, 67, 'sarai.stein@yahoo.com','saraiiii7'),
('Zina Near', 145, 76, 'zina.near@hotmail.com','zinaisasina5'),
('Lizzie Gilbert', 151, 59, 'lizzie.gilbert@yahoo.com','lizliz3'),
('Tiesha Pierce', 190, 99, 'tiesha.pierce@yahoo.com','dt567576'),
('Armand Halpert', 176, 75, 'armand.halpert@hotmail.com','whiteyytt4'),
('Teofila Price', 172, 74, 'teofila.price@aol.com','fishfingers2'),
('Lissa Beasley',160, 70, 'lissa.beasley@yahoo.com','lemonlissa6'),
('Yan Combs',186, 70, 'yan.combs@yahoo.com','yams333'),
('Titus Strong', 199, 98, 'titus.strong@hotmail.com','chocolatecake6'),
('Arvilla Adams', 167, 77, 'arvilla.adams@hotmail.com','arisborn1'),
('Marjorie Young', 167, 78, 'marjorie.young@yahoo.com','95franklin'),
('Marvin Moon', 191, 81, 'marvin.moon@aol.com','mm777766655'),
('Tena Lipton', 165, 70, 'tena.lipton@yahoo.com','finally!');


select * from user_data;
